<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Kure</title>
	</head>
	<body>
		<div id="status">Vrata: {DOOR} Luč: {LIGHT} Temperatura: {T:0.2f}°C Vlažnost: {H:0.2f}% @{TIMESTAMP}</div>
		<form method="POST">
    		<p>Vrata: {DOOR}</p>
		    <button type="submit" value="door_up">ODPRI</button>
		    <button type="submit" value="door_down">ZAPRI</button>
    		<p>IR luč: {LIGHT}</p>
		    <button type="submit" value="light_on">ODPRI</button>
		    <button type="submit" value="light_off">ZAPRI</button>
        </form>
	</body>
</html>
